name: new Release
on:
  push:
    tags:
      - v*

jobs:
  build-publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: GitHub Container Registry Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: octodemobo
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Container
        id: container_publish
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            VERSION=${{github.ref_name}}
            REPOSITORY_NAME=${{ github.repository }}
            revision=${{ github.sha }}
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{github.ref_name}}


  deploy-to-kubernetes:
    uses: tgrall-gitops/tug-sample-app/.github/workflows/deploy-to-aks.yml@main
    needs: [ build-publish-docker-image ]
    with:
      resource-group: tgrall-demo
      cluster-name: tug-kube
      namespace : production
      environment : production
      branch : ${{ github.ref_name }}
    secrets:
      client-id: ${{ secrets.AZURE_CLIENT_ID }}
      tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}     